version: '3'
services:
  react-app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - react-app-node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  flask-api:
    build: 
      context: ../api
      dockerfile: ../api/Dockerfile
    volumes:
      - ../api:/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: NEW_DB
      DB_USER: postgres
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: NEW_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  react-app-node_modules:
  db-data: